on:
  push:
    branches:
    - '**'
    paths:
    - repos/fdbt-admin/**
  workflow_dispatch:

name: 'fdbt-admin'

defaults:
  run:
    working-directory: ./repos/fdbt-admin

jobs:

  fdbt-admin_to_deploy:
    name: 'fdbt-admin'
    runs-on: ubuntu-latest
    env:
      WORKSPACE: none
    
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
